// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Enum_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace Protobuf {

enum OBJECT_TYPE : int {
  OBJECT_TYPE_NONE = 0,
  OBJECT_TYPE_PLAYER = 1,
  OBJECT_TYPE_BULLET = 2,
  OBJECT_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  OBJECT_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool OBJECT_TYPE_IsValid(int value);
constexpr OBJECT_TYPE OBJECT_TYPE_MIN = OBJECT_TYPE_NONE;
constexpr OBJECT_TYPE OBJECT_TYPE_MAX = OBJECT_TYPE_BULLET;
constexpr int OBJECT_TYPE_ARRAYSIZE = OBJECT_TYPE_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* OBJECT_TYPE_descriptor();
template<typename T>
inline const std::string& OBJECT_TYPE_Name(T enum_t_value) {
  static_assert(::std::is_same<T, OBJECT_TYPE>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function OBJECT_TYPE_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    OBJECT_TYPE_descriptor(), enum_t_value);
}
inline bool OBJECT_TYPE_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, OBJECT_TYPE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<OBJECT_TYPE>(
    OBJECT_TYPE_descriptor(), name, value);
}
enum OBJECT_STATE_TYPE : int {
  OBJECT_STATE_TYPE_IDLE = 0,
  OBJECT_STATE_TYPE_WALK = 1,
  OBJECT_STATE_TYPE_RUN = 2,
  OBJECT_STATE_TYPE_JUMP = 3,
  OBJECT_STATE_TYPE_LAND = 4,
  OBJECT_STATE_TYPE_SLIDE = 5,
  OBJECT_STATE_TYPE_DASH = 6,
  OBJECT_STATE_TYPE_CLIMB = 7,
  OBJECT_STATE_TYPE_AIR_ATTACK = 8,
  OBJECT_STATE_TYPE_ATTACK_1 = 9,
  OBJECT_STATE_TYPE_ATTACK_2 = 10,
  OBJECT_STATE_TYPE_ATTACK_3 = 11,
  OBJECT_STATE_TYPE_SHOT = 12,
  OBJECT_STATE_TYPE_HIT = 13,
  OBJECT_STATE_TYPE_DEATH = 14,
  OBJECT_STATE_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  OBJECT_STATE_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool OBJECT_STATE_TYPE_IsValid(int value);
constexpr OBJECT_STATE_TYPE OBJECT_STATE_TYPE_MIN = OBJECT_STATE_TYPE_IDLE;
constexpr OBJECT_STATE_TYPE OBJECT_STATE_TYPE_MAX = OBJECT_STATE_TYPE_DEATH;
constexpr int OBJECT_STATE_TYPE_ARRAYSIZE = OBJECT_STATE_TYPE_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* OBJECT_STATE_TYPE_descriptor();
template<typename T>
inline const std::string& OBJECT_STATE_TYPE_Name(T enum_t_value) {
  static_assert(::std::is_same<T, OBJECT_STATE_TYPE>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function OBJECT_STATE_TYPE_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    OBJECT_STATE_TYPE_descriptor(), enum_t_value);
}
inline bool OBJECT_STATE_TYPE_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, OBJECT_STATE_TYPE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<OBJECT_STATE_TYPE>(
    OBJECT_STATE_TYPE_descriptor(), name, value);
}
enum DIR_TYPE : int {
  DIR_TYPE_NONE = 0,
  DIR_TYPE_UP = 1,
  DIR_TYPE_DOWN = 2,
  DIR_TYPE_LEFT = 3,
  DIR_TYPE_RIGHT = 4,
  DIR_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  DIR_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool DIR_TYPE_IsValid(int value);
constexpr DIR_TYPE DIR_TYPE_MIN = DIR_TYPE_NONE;
constexpr DIR_TYPE DIR_TYPE_MAX = DIR_TYPE_RIGHT;
constexpr int DIR_TYPE_ARRAYSIZE = DIR_TYPE_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DIR_TYPE_descriptor();
template<typename T>
inline const std::string& DIR_TYPE_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DIR_TYPE>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DIR_TYPE_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DIR_TYPE_descriptor(), enum_t_value);
}
inline bool DIR_TYPE_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DIR_TYPE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DIR_TYPE>(
    DIR_TYPE_descriptor(), name, value);
}
enum FACING_TYPE : int {
  FACING_TYPE_LEFT = 0,
  FACING_TYPE_RIGHT = 1,
  FACING_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  FACING_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool FACING_TYPE_IsValid(int value);
constexpr FACING_TYPE FACING_TYPE_MIN = FACING_TYPE_LEFT;
constexpr FACING_TYPE FACING_TYPE_MAX = FACING_TYPE_RIGHT;
constexpr int FACING_TYPE_ARRAYSIZE = FACING_TYPE_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* FACING_TYPE_descriptor();
template<typename T>
inline const std::string& FACING_TYPE_Name(T enum_t_value) {
  static_assert(::std::is_same<T, FACING_TYPE>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function FACING_TYPE_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    FACING_TYPE_descriptor(), enum_t_value);
}
inline bool FACING_TYPE_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, FACING_TYPE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<FACING_TYPE>(
    FACING_TYPE_descriptor(), name, value);
}
enum WEAPON_TYPE : int {
  WEAPON_TYPE_NONE = 0,
  WEAPON_TYPE_PISTOL = 1,
  WEAPON_TYPE_SWORD = 2,
  WEAPON_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  WEAPON_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool WEAPON_TYPE_IsValid(int value);
constexpr WEAPON_TYPE WEAPON_TYPE_MIN = WEAPON_TYPE_NONE;
constexpr WEAPON_TYPE WEAPON_TYPE_MAX = WEAPON_TYPE_SWORD;
constexpr int WEAPON_TYPE_ARRAYSIZE = WEAPON_TYPE_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* WEAPON_TYPE_descriptor();
template<typename T>
inline const std::string& WEAPON_TYPE_Name(T enum_t_value) {
  static_assert(::std::is_same<T, WEAPON_TYPE>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function WEAPON_TYPE_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    WEAPON_TYPE_descriptor(), enum_t_value);
}
inline bool WEAPON_TYPE_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, WEAPON_TYPE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<WEAPON_TYPE>(
    WEAPON_TYPE_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protobuf

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Protobuf::OBJECT_TYPE> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protobuf::OBJECT_TYPE>() {
  return ::Protobuf::OBJECT_TYPE_descriptor();
}
template <> struct is_proto_enum< ::Protobuf::OBJECT_STATE_TYPE> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protobuf::OBJECT_STATE_TYPE>() {
  return ::Protobuf::OBJECT_STATE_TYPE_descriptor();
}
template <> struct is_proto_enum< ::Protobuf::DIR_TYPE> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protobuf::DIR_TYPE>() {
  return ::Protobuf::DIR_TYPE_descriptor();
}
template <> struct is_proto_enum< ::Protobuf::FACING_TYPE> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protobuf::FACING_TYPE>() {
  return ::Protobuf::FACING_TYPE_descriptor();
}
template <> struct is_proto_enum< ::Protobuf::WEAPON_TYPE> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protobuf::WEAPON_TYPE>() {
  return ::Protobuf::WEAPON_TYPE_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
