syntax = "proto3";
package Protobuf;

enum OBJECT_TYPE
{
	OBJECT_TYPE_NONE = 0;
	OBJECT_TYPE_PLAYER = 1;
	OBJECT_TYPE_BULLET = 3;
}

enum OBJECT_STATE_TYPE
{
	OBJECT_STATE_TYPE_IDLE = 0;
	OBJECT_STATE_TYPE_WALK = 1;
	OBJECT_STATE_TYPE_RUN = 2;
	OBJECT_STATE_TYPE_JUMP = 3;
	OBJECT_STATE_TYPE_FALL = 4;
	OBJECT_STATE_TYPE_SLIDE = 5;
	OBJECT_STATE_TYPE_DASH = 6;
	OBJECT_STATE_TYPE_CLIMB = 7;
	OBJECT_STATE_TYPE_AIR_ATTACK = 8;
	OBJECT_STATE_TYPE_ATTACK_1 = 9;
	OBJECT_STATE_TYPE_ATTACK_2 = 10;
	OBJECT_STATE_TYPE_ATTACK_3 = 11;
	OBJECT_STATE_TYPE_SHOT = 12;
	OBJECT_STATE_TYPE_HIT = 13;
	OBJECT_STATE_TYPE_DEATH = 14;
}

enum DIR_TYPE
{
	DIR_TYPE_NONE = 0;
	DIR_TYPE_UP = 1;
	DIR_TYPE_DOWN = 2;
	DIR_TYPE_LEFT = 3;
	DIR_TYPE_RIGHT = 4;
}

enum FACING_TYPE
{
	FACING_TYPE_LEFT = 0;
	FACING_TYPE_RIGHT = 1;
}

enum WEAPON_TYPE
{
	WEAPON_TYPE_NONE = 0;
	WEAPON_TYPE_PISTOL = 1;
	WEAPON_TYPE_SWORD = 2;
}