// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#include "Enum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protobuf {
}  // namespace Protobuf
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_Enum_2eproto[5];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Enum_2eproto = nullptr;
const uint32_t TableStruct_Enum_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_Enum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nEnum.proto\022\010Protobuf*S\n\013OBJECT_TYPE\022\024\n"
  "\020OBJECT_TYPE_NONE\020\000\022\026\n\022OBJECT_TYPE_PLAYE"
  "R\020\001\022\026\n\022OBJECT_TYPE_BULLET\020\002*\312\003\n\021OBJECT_S"
  "TATE_TYPE\022\032\n\026OBJECT_STATE_TYPE_IDLE\020\000\022\032\n"
  "\026OBJECT_STATE_TYPE_WALK\020\001\022\031\n\025OBJECT_STAT"
  "E_TYPE_RUN\020\002\022\032\n\026OBJECT_STATE_TYPE_JUMP\020\003"
  "\022\032\n\026OBJECT_STATE_TYPE_FALL\020\004\022\033\n\027OBJECT_S"
  "TATE_TYPE_SLIDE\020\005\022\032\n\026OBJECT_STATE_TYPE_D"
  "ASH\020\006\022\033\n\027OBJECT_STATE_TYPE_CLIMB\020\007\022 \n\034OB"
  "JECT_STATE_TYPE_AIR_ATTACK\020\010\022\036\n\032OBJECT_S"
  "TATE_TYPE_ATTACK_1\020\t\022\036\n\032OBJECT_STATE_TYP"
  "E_ATTACK_2\020\n\022\036\n\032OBJECT_STATE_TYPE_ATTACK"
  "_3\020\013\022\032\n\026OBJECT_STATE_TYPE_SHOT\020\014\022\031\n\025OBJE"
  "CT_STATE_TYPE_HIT\020\r\022\033\n\027OBJECT_STATE_TYPE"
  "_DEATH\020\016*h\n\010DIR_TYPE\022\021\n\rDIR_TYPE_NONE\020\000\022"
  "\017\n\013DIR_TYPE_UP\020\001\022\021\n\rDIR_TYPE_DOWN\020\002\022\021\n\rD"
  "IR_TYPE_LEFT\020\003\022\022\n\016DIR_TYPE_RIGHT\020\004*:\n\013FA"
  "CING_TYPE\022\024\n\020FACING_TYPE_LEFT\020\000\022\025\n\021FACIN"
  "G_TYPE_RIGHT\020\001*R\n\013WEAPON_TYPE\022\024\n\020WEAPON_"
  "TYPE_NONE\020\000\022\026\n\022WEAPON_TYPE_PISTOL\020\001\022\025\n\021W"
  "EAPON_TYPE_SWORD\020\002b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_Enum_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Enum_2eproto = {
    false, false, 826, descriptor_table_protodef_Enum_2eproto,
    "Enum.proto",
    &descriptor_table_Enum_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_Enum_2eproto::offsets,
    nullptr, file_level_enum_descriptors_Enum_2eproto,
    file_level_service_descriptors_Enum_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Enum_2eproto_getter() {
  return &descriptor_table_Enum_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Enum_2eproto(&descriptor_table_Enum_2eproto);
namespace Protobuf {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* OBJECT_TYPE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[0];
}
bool OBJECT_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* OBJECT_STATE_TYPE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[1];
}
bool OBJECT_STATE_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DIR_TYPE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[2];
}
bool DIR_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* FACING_TYPE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[3];
}
bool FACING_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* WEAPON_TYPE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[4];
}
bool WEAPON_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Protobuf
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
