syntax = "proto3";
package Protobuf;

import "Enum.proto";
import "Struct.proto";

/*=====================//
//   Client Packets    //
//=====================*/
message C_EnterGame { }
message C_Jump { }
message C_Attack { }

message C_Move
{
    DIR_TYPE horizontal_dir = 1;
    DIR_TYPE vertical_dir = 2;
    bool running = 3;
}

message C_ChangeWeapon
{
    WEAPON_TYPE weapon = 1;
}

/*=====================//
//   Server Packets    //
//=====================*/
message S_EnterGame
{
	bool success = 1;
	PlayerInfo player = 2;
}

message S_SpawnPlayer
{
    repeated PlayerInfo objects = 1;
}

message S_RemovePlayer
{

}

message S_SyncPlayers
{
    repeated PlayerInfo objects = 1;
}

message S_SpawnBullet
{

}

message S_RemoveBullet
{

}

message S_SyncBullet
{

}

