syntax = "proto3";
package Protobuf;

import "Enum.proto";
import "Types.proto";

/*=========================//
//   Player sync struct    //
//=========================*/
message PlayerInfo
{
	uint64 objectID = 1;
	OBJECT_TYPE objectType = 2;
	OBJECT_STATE_TYPE state = 3;
	Vec2 position = 4;
    Vec2 velocity = 5;
	bool grounded = 6;
    FACING_TYPE facing = 7;
    WEAPON_TYPE weapon = 8;
    Color color = 9;
    bool invincible = 10;
    uint32 life = 11;
    uint32 kill_cnt = 12;
}

/*==========================//
//   Bullet sync Packets    //
//==========================*/
message BulletInfo
{
	uint64 objectID = 1;
    uint64 ownerID = 2;
    Vec2 position = 3;
    Vec2 velocity = 4;
    FACING_TYPE facing = 5;
    Color color = 6;
}