// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Struct.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
#include "Types.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Struct_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Struct_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Struct_2eproto;
namespace Protobuf {
class ObjectInfo;
struct ObjectInfoDefaultTypeInternal;
extern ObjectInfoDefaultTypeInternal _ObjectInfo_default_instance_;
}  // namespace Protobuf
PROTOBUF_NAMESPACE_OPEN
template<> ::Protobuf::ObjectInfo* Arena::CreateMaybeMessage<::Protobuf::ObjectInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protobuf {

// ===================================================================

class ObjectInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protobuf.ObjectInfo) */ {
 public:
  inline ObjectInfo() : ObjectInfo(nullptr) {}
  ~ObjectInfo() override;
  explicit PROTOBUF_CONSTEXPR ObjectInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ObjectInfo(const ObjectInfo& from);
  ObjectInfo(ObjectInfo&& from) noexcept
    : ObjectInfo() {
    *this = ::std::move(from);
  }

  inline ObjectInfo& operator=(const ObjectInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObjectInfo& operator=(ObjectInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ObjectInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ObjectInfo* internal_default_instance() {
    return reinterpret_cast<const ObjectInfo*>(
               &_ObjectInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ObjectInfo& a, ObjectInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ObjectInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ObjectInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ObjectInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ObjectInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ObjectInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ObjectInfo& from) {
    ObjectInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObjectInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protobuf.ObjectInfo";
  }
  protected:
  explicit ObjectInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 4,
    kVelocityFieldNumber = 5,
    kColorFieldNumber = 9,
    kObjectIDFieldNumber = 1,
    kObjectTypeFieldNumber = 2,
    kStateFieldNumber = 3,
    kGroundedFieldNumber = 6,
    kFacingFieldNumber = 7,
    kWeaponFieldNumber = 8,
  };
  // .Protobuf.Vec2 position = 4;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::Protobuf::Vec2& position() const;
  PROTOBUF_NODISCARD ::Protobuf::Vec2* release_position();
  ::Protobuf::Vec2* mutable_position();
  void set_allocated_position(::Protobuf::Vec2* position);
  private:
  const ::Protobuf::Vec2& _internal_position() const;
  ::Protobuf::Vec2* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::Protobuf::Vec2* position);
  ::Protobuf::Vec2* unsafe_arena_release_position();

  // .Protobuf.Vec2 velocity = 5;
  bool has_velocity() const;
  private:
  bool _internal_has_velocity() const;
  public:
  void clear_velocity();
  const ::Protobuf::Vec2& velocity() const;
  PROTOBUF_NODISCARD ::Protobuf::Vec2* release_velocity();
  ::Protobuf::Vec2* mutable_velocity();
  void set_allocated_velocity(::Protobuf::Vec2* velocity);
  private:
  const ::Protobuf::Vec2& _internal_velocity() const;
  ::Protobuf::Vec2* _internal_mutable_velocity();
  public:
  void unsafe_arena_set_allocated_velocity(
      ::Protobuf::Vec2* velocity);
  ::Protobuf::Vec2* unsafe_arena_release_velocity();

  // .Protobuf.Color color = 9;
  bool has_color() const;
  private:
  bool _internal_has_color() const;
  public:
  void clear_color();
  const ::Protobuf::Color& color() const;
  PROTOBUF_NODISCARD ::Protobuf::Color* release_color();
  ::Protobuf::Color* mutable_color();
  void set_allocated_color(::Protobuf::Color* color);
  private:
  const ::Protobuf::Color& _internal_color() const;
  ::Protobuf::Color* _internal_mutable_color();
  public:
  void unsafe_arena_set_allocated_color(
      ::Protobuf::Color* color);
  ::Protobuf::Color* unsafe_arena_release_color();

  // uint64 objectID = 1;
  void clear_objectid();
  uint64_t objectid() const;
  void set_objectid(uint64_t value);
  private:
  uint64_t _internal_objectid() const;
  void _internal_set_objectid(uint64_t value);
  public:

  // .Protobuf.OBJECT_TYPE objectType = 2;
  void clear_objecttype();
  ::Protobuf::OBJECT_TYPE objecttype() const;
  void set_objecttype(::Protobuf::OBJECT_TYPE value);
  private:
  ::Protobuf::OBJECT_TYPE _internal_objecttype() const;
  void _internal_set_objecttype(::Protobuf::OBJECT_TYPE value);
  public:

  // .Protobuf.OBJECT_STATE_TYPE state = 3;
  void clear_state();
  ::Protobuf::OBJECT_STATE_TYPE state() const;
  void set_state(::Protobuf::OBJECT_STATE_TYPE value);
  private:
  ::Protobuf::OBJECT_STATE_TYPE _internal_state() const;
  void _internal_set_state(::Protobuf::OBJECT_STATE_TYPE value);
  public:

  // bool grounded = 6;
  void clear_grounded();
  bool grounded() const;
  void set_grounded(bool value);
  private:
  bool _internal_grounded() const;
  void _internal_set_grounded(bool value);
  public:

  // .Protobuf.FACING_TYPE facing = 7;
  void clear_facing();
  ::Protobuf::FACING_TYPE facing() const;
  void set_facing(::Protobuf::FACING_TYPE value);
  private:
  ::Protobuf::FACING_TYPE _internal_facing() const;
  void _internal_set_facing(::Protobuf::FACING_TYPE value);
  public:

  // .Protobuf.WEAPON_TYPE weapon = 8;
  void clear_weapon();
  ::Protobuf::WEAPON_TYPE weapon() const;
  void set_weapon(::Protobuf::WEAPON_TYPE value);
  private:
  ::Protobuf::WEAPON_TYPE _internal_weapon() const;
  void _internal_set_weapon(::Protobuf::WEAPON_TYPE value);
  public:

  // @@protoc_insertion_point(class_scope:Protobuf.ObjectInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protobuf::Vec2* position_;
    ::Protobuf::Vec2* velocity_;
    ::Protobuf::Color* color_;
    uint64_t objectid_;
    int objecttype_;
    int state_;
    bool grounded_;
    int facing_;
    int weapon_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ObjectInfo

// uint64 objectID = 1;
inline void ObjectInfo::clear_objectid() {
  _impl_.objectid_ = uint64_t{0u};
}
inline uint64_t ObjectInfo::_internal_objectid() const {
  return _impl_.objectid_;
}
inline uint64_t ObjectInfo::objectid() const {
  // @@protoc_insertion_point(field_get:Protobuf.ObjectInfo.objectID)
  return _internal_objectid();
}
inline void ObjectInfo::_internal_set_objectid(uint64_t value) {
  
  _impl_.objectid_ = value;
}
inline void ObjectInfo::set_objectid(uint64_t value) {
  _internal_set_objectid(value);
  // @@protoc_insertion_point(field_set:Protobuf.ObjectInfo.objectID)
}

// .Protobuf.OBJECT_TYPE objectType = 2;
inline void ObjectInfo::clear_objecttype() {
  _impl_.objecttype_ = 0;
}
inline ::Protobuf::OBJECT_TYPE ObjectInfo::_internal_objecttype() const {
  return static_cast< ::Protobuf::OBJECT_TYPE >(_impl_.objecttype_);
}
inline ::Protobuf::OBJECT_TYPE ObjectInfo::objecttype() const {
  // @@protoc_insertion_point(field_get:Protobuf.ObjectInfo.objectType)
  return _internal_objecttype();
}
inline void ObjectInfo::_internal_set_objecttype(::Protobuf::OBJECT_TYPE value) {
  
  _impl_.objecttype_ = value;
}
inline void ObjectInfo::set_objecttype(::Protobuf::OBJECT_TYPE value) {
  _internal_set_objecttype(value);
  // @@protoc_insertion_point(field_set:Protobuf.ObjectInfo.objectType)
}

// .Protobuf.OBJECT_STATE_TYPE state = 3;
inline void ObjectInfo::clear_state() {
  _impl_.state_ = 0;
}
inline ::Protobuf::OBJECT_STATE_TYPE ObjectInfo::_internal_state() const {
  return static_cast< ::Protobuf::OBJECT_STATE_TYPE >(_impl_.state_);
}
inline ::Protobuf::OBJECT_STATE_TYPE ObjectInfo::state() const {
  // @@protoc_insertion_point(field_get:Protobuf.ObjectInfo.state)
  return _internal_state();
}
inline void ObjectInfo::_internal_set_state(::Protobuf::OBJECT_STATE_TYPE value) {
  
  _impl_.state_ = value;
}
inline void ObjectInfo::set_state(::Protobuf::OBJECT_STATE_TYPE value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:Protobuf.ObjectInfo.state)
}

// .Protobuf.Vec2 position = 4;
inline bool ObjectInfo::_internal_has_position() const {
  return this != internal_default_instance() && _impl_.position_ != nullptr;
}
inline bool ObjectInfo::has_position() const {
  return _internal_has_position();
}
inline const ::Protobuf::Vec2& ObjectInfo::_internal_position() const {
  const ::Protobuf::Vec2* p = _impl_.position_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protobuf::Vec2&>(
      ::Protobuf::_Vec2_default_instance_);
}
inline const ::Protobuf::Vec2& ObjectInfo::position() const {
  // @@protoc_insertion_point(field_get:Protobuf.ObjectInfo.position)
  return _internal_position();
}
inline void ObjectInfo::unsafe_arena_set_allocated_position(
    ::Protobuf::Vec2* position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.position_);
  }
  _impl_.position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protobuf.ObjectInfo.position)
}
inline ::Protobuf::Vec2* ObjectInfo::release_position() {
  
  ::Protobuf::Vec2* temp = _impl_.position_;
  _impl_.position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protobuf::Vec2* ObjectInfo::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:Protobuf.ObjectInfo.position)
  
  ::Protobuf::Vec2* temp = _impl_.position_;
  _impl_.position_ = nullptr;
  return temp;
}
inline ::Protobuf::Vec2* ObjectInfo::_internal_mutable_position() {
  
  if (_impl_.position_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protobuf::Vec2>(GetArenaForAllocation());
    _impl_.position_ = p;
  }
  return _impl_.position_;
}
inline ::Protobuf::Vec2* ObjectInfo::mutable_position() {
  ::Protobuf::Vec2* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:Protobuf.ObjectInfo.position)
  return _msg;
}
inline void ObjectInfo::set_allocated_position(::Protobuf::Vec2* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.position_);
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position));
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.position_ = position;
  // @@protoc_insertion_point(field_set_allocated:Protobuf.ObjectInfo.position)
}

// .Protobuf.Vec2 velocity = 5;
inline bool ObjectInfo::_internal_has_velocity() const {
  return this != internal_default_instance() && _impl_.velocity_ != nullptr;
}
inline bool ObjectInfo::has_velocity() const {
  return _internal_has_velocity();
}
inline const ::Protobuf::Vec2& ObjectInfo::_internal_velocity() const {
  const ::Protobuf::Vec2* p = _impl_.velocity_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protobuf::Vec2&>(
      ::Protobuf::_Vec2_default_instance_);
}
inline const ::Protobuf::Vec2& ObjectInfo::velocity() const {
  // @@protoc_insertion_point(field_get:Protobuf.ObjectInfo.velocity)
  return _internal_velocity();
}
inline void ObjectInfo::unsafe_arena_set_allocated_velocity(
    ::Protobuf::Vec2* velocity) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.velocity_);
  }
  _impl_.velocity_ = velocity;
  if (velocity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protobuf.ObjectInfo.velocity)
}
inline ::Protobuf::Vec2* ObjectInfo::release_velocity() {
  
  ::Protobuf::Vec2* temp = _impl_.velocity_;
  _impl_.velocity_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protobuf::Vec2* ObjectInfo::unsafe_arena_release_velocity() {
  // @@protoc_insertion_point(field_release:Protobuf.ObjectInfo.velocity)
  
  ::Protobuf::Vec2* temp = _impl_.velocity_;
  _impl_.velocity_ = nullptr;
  return temp;
}
inline ::Protobuf::Vec2* ObjectInfo::_internal_mutable_velocity() {
  
  if (_impl_.velocity_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protobuf::Vec2>(GetArenaForAllocation());
    _impl_.velocity_ = p;
  }
  return _impl_.velocity_;
}
inline ::Protobuf::Vec2* ObjectInfo::mutable_velocity() {
  ::Protobuf::Vec2* _msg = _internal_mutable_velocity();
  // @@protoc_insertion_point(field_mutable:Protobuf.ObjectInfo.velocity)
  return _msg;
}
inline void ObjectInfo::set_allocated_velocity(::Protobuf::Vec2* velocity) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.velocity_);
  }
  if (velocity) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(velocity));
    if (message_arena != submessage_arena) {
      velocity = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, velocity, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.velocity_ = velocity;
  // @@protoc_insertion_point(field_set_allocated:Protobuf.ObjectInfo.velocity)
}

// bool grounded = 6;
inline void ObjectInfo::clear_grounded() {
  _impl_.grounded_ = false;
}
inline bool ObjectInfo::_internal_grounded() const {
  return _impl_.grounded_;
}
inline bool ObjectInfo::grounded() const {
  // @@protoc_insertion_point(field_get:Protobuf.ObjectInfo.grounded)
  return _internal_grounded();
}
inline void ObjectInfo::_internal_set_grounded(bool value) {
  
  _impl_.grounded_ = value;
}
inline void ObjectInfo::set_grounded(bool value) {
  _internal_set_grounded(value);
  // @@protoc_insertion_point(field_set:Protobuf.ObjectInfo.grounded)
}

// .Protobuf.FACING_TYPE facing = 7;
inline void ObjectInfo::clear_facing() {
  _impl_.facing_ = 0;
}
inline ::Protobuf::FACING_TYPE ObjectInfo::_internal_facing() const {
  return static_cast< ::Protobuf::FACING_TYPE >(_impl_.facing_);
}
inline ::Protobuf::FACING_TYPE ObjectInfo::facing() const {
  // @@protoc_insertion_point(field_get:Protobuf.ObjectInfo.facing)
  return _internal_facing();
}
inline void ObjectInfo::_internal_set_facing(::Protobuf::FACING_TYPE value) {
  
  _impl_.facing_ = value;
}
inline void ObjectInfo::set_facing(::Protobuf::FACING_TYPE value) {
  _internal_set_facing(value);
  // @@protoc_insertion_point(field_set:Protobuf.ObjectInfo.facing)
}

// .Protobuf.WEAPON_TYPE weapon = 8;
inline void ObjectInfo::clear_weapon() {
  _impl_.weapon_ = 0;
}
inline ::Protobuf::WEAPON_TYPE ObjectInfo::_internal_weapon() const {
  return static_cast< ::Protobuf::WEAPON_TYPE >(_impl_.weapon_);
}
inline ::Protobuf::WEAPON_TYPE ObjectInfo::weapon() const {
  // @@protoc_insertion_point(field_get:Protobuf.ObjectInfo.weapon)
  return _internal_weapon();
}
inline void ObjectInfo::_internal_set_weapon(::Protobuf::WEAPON_TYPE value) {
  
  _impl_.weapon_ = value;
}
inline void ObjectInfo::set_weapon(::Protobuf::WEAPON_TYPE value) {
  _internal_set_weapon(value);
  // @@protoc_insertion_point(field_set:Protobuf.ObjectInfo.weapon)
}

// .Protobuf.Color color = 9;
inline bool ObjectInfo::_internal_has_color() const {
  return this != internal_default_instance() && _impl_.color_ != nullptr;
}
inline bool ObjectInfo::has_color() const {
  return _internal_has_color();
}
inline const ::Protobuf::Color& ObjectInfo::_internal_color() const {
  const ::Protobuf::Color* p = _impl_.color_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protobuf::Color&>(
      ::Protobuf::_Color_default_instance_);
}
inline const ::Protobuf::Color& ObjectInfo::color() const {
  // @@protoc_insertion_point(field_get:Protobuf.ObjectInfo.color)
  return _internal_color();
}
inline void ObjectInfo::unsafe_arena_set_allocated_color(
    ::Protobuf::Color* color) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.color_);
  }
  _impl_.color_ = color;
  if (color) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protobuf.ObjectInfo.color)
}
inline ::Protobuf::Color* ObjectInfo::release_color() {
  
  ::Protobuf::Color* temp = _impl_.color_;
  _impl_.color_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protobuf::Color* ObjectInfo::unsafe_arena_release_color() {
  // @@protoc_insertion_point(field_release:Protobuf.ObjectInfo.color)
  
  ::Protobuf::Color* temp = _impl_.color_;
  _impl_.color_ = nullptr;
  return temp;
}
inline ::Protobuf::Color* ObjectInfo::_internal_mutable_color() {
  
  if (_impl_.color_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protobuf::Color>(GetArenaForAllocation());
    _impl_.color_ = p;
  }
  return _impl_.color_;
}
inline ::Protobuf::Color* ObjectInfo::mutable_color() {
  ::Protobuf::Color* _msg = _internal_mutable_color();
  // @@protoc_insertion_point(field_mutable:Protobuf.ObjectInfo.color)
  return _msg;
}
inline void ObjectInfo::set_allocated_color(::Protobuf::Color* color) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.color_);
  }
  if (color) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(color));
    if (message_arena != submessage_arena) {
      color = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, color, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.color_ = color;
  // @@protoc_insertion_point(field_set_allocated:Protobuf.ObjectInfo.color)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protobuf

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
