// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Struct.proto

#include "Struct.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protobuf {
PROTOBUF_CONSTEXPR PlayerInfo::PlayerInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.position_)*/nullptr
  , /*decltype(_impl_.velocity_)*/nullptr
  , /*decltype(_impl_.color_)*/nullptr
  , /*decltype(_impl_.objectid_)*/uint64_t{0u}
  , /*decltype(_impl_.objecttype_)*/0
  , /*decltype(_impl_.state_)*/0
  , /*decltype(_impl_.facing_)*/0
  , /*decltype(_impl_.weapon_)*/0
  , /*decltype(_impl_.grounded_)*/false
  , /*decltype(_impl_.invincible_)*/false
  , /*decltype(_impl_.life_)*/0u
  , /*decltype(_impl_.kill_cnt_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PlayerInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerInfoDefaultTypeInternal() {}
  union {
    PlayerInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerInfoDefaultTypeInternal _PlayerInfo_default_instance_;
PROTOBUF_CONSTEXPR BulletInfo::BulletInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.position_)*/nullptr
  , /*decltype(_impl_.velocity_)*/nullptr
  , /*decltype(_impl_.color_)*/nullptr
  , /*decltype(_impl_.objectid_)*/uint64_t{0u}
  , /*decltype(_impl_.ownerid_)*/uint64_t{0u}
  , /*decltype(_impl_.facing_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BulletInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BulletInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BulletInfoDefaultTypeInternal() {}
  union {
    BulletInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BulletInfoDefaultTypeInternal _BulletInfo_default_instance_;
}  // namespace Protobuf
static ::_pb::Metadata file_level_metadata_Struct_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Struct_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Struct_2eproto = nullptr;

const uint32_t TableStruct_Struct_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protobuf::PlayerInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protobuf::PlayerInfo, _impl_.objectid_),
  PROTOBUF_FIELD_OFFSET(::Protobuf::PlayerInfo, _impl_.objecttype_),
  PROTOBUF_FIELD_OFFSET(::Protobuf::PlayerInfo, _impl_.state_),
  PROTOBUF_FIELD_OFFSET(::Protobuf::PlayerInfo, _impl_.position_),
  PROTOBUF_FIELD_OFFSET(::Protobuf::PlayerInfo, _impl_.velocity_),
  PROTOBUF_FIELD_OFFSET(::Protobuf::PlayerInfo, _impl_.grounded_),
  PROTOBUF_FIELD_OFFSET(::Protobuf::PlayerInfo, _impl_.facing_),
  PROTOBUF_FIELD_OFFSET(::Protobuf::PlayerInfo, _impl_.weapon_),
  PROTOBUF_FIELD_OFFSET(::Protobuf::PlayerInfo, _impl_.color_),
  PROTOBUF_FIELD_OFFSET(::Protobuf::PlayerInfo, _impl_.invincible_),
  PROTOBUF_FIELD_OFFSET(::Protobuf::PlayerInfo, _impl_.life_),
  PROTOBUF_FIELD_OFFSET(::Protobuf::PlayerInfo, _impl_.kill_cnt_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protobuf::BulletInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protobuf::BulletInfo, _impl_.objectid_),
  PROTOBUF_FIELD_OFFSET(::Protobuf::BulletInfo, _impl_.ownerid_),
  PROTOBUF_FIELD_OFFSET(::Protobuf::BulletInfo, _impl_.position_),
  PROTOBUF_FIELD_OFFSET(::Protobuf::BulletInfo, _impl_.velocity_),
  PROTOBUF_FIELD_OFFSET(::Protobuf::BulletInfo, _impl_.facing_),
  PROTOBUF_FIELD_OFFSET(::Protobuf::BulletInfo, _impl_.color_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protobuf::PlayerInfo)},
  { 18, -1, -1, sizeof(::Protobuf::BulletInfo)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protobuf::_PlayerInfo_default_instance_._instance,
  &::Protobuf::_BulletInfo_default_instance_._instance,
};

const char descriptor_table_protodef_Struct_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014Struct.proto\022\010Protobuf\032\nEnum.proto\032\013Ty"
  "pes.proto\"\355\002\n\nPlayerInfo\022\020\n\010objectID\030\001 \001"
  "(\004\022)\n\nobjectType\030\002 \001(\0162\025.Protobuf.OBJECT"
  "_TYPE\022*\n\005state\030\003 \001(\0162\033.Protobuf.OBJECT_S"
  "TATE_TYPE\022 \n\010position\030\004 \001(\0132\016.Protobuf.V"
  "ec2\022 \n\010velocity\030\005 \001(\0132\016.Protobuf.Vec2\022\020\n"
  "\010grounded\030\006 \001(\010\022%\n\006facing\030\007 \001(\0162\025.Protob"
  "uf.FACING_TYPE\022%\n\006weapon\030\010 \001(\0162\025.Protobu"
  "f.WEAPON_TYPE\022\036\n\005color\030\t \001(\0132\017.Protobuf."
  "Color\022\022\n\ninvincible\030\n \001(\010\022\014\n\004life\030\013 \001(\r\022"
  "\020\n\010kill_cnt\030\014 \001(\r\"\272\001\n\nBulletInfo\022\020\n\010obje"
  "ctID\030\001 \001(\004\022\017\n\007ownerID\030\002 \001(\004\022 \n\010position\030"
  "\003 \001(\0132\016.Protobuf.Vec2\022 \n\010velocity\030\004 \001(\0132"
  "\016.Protobuf.Vec2\022%\n\006facing\030\005 \001(\0162\025.Protob"
  "uf.FACING_TYPE\022\036\n\005color\030\006 \001(\0132\017.Protobuf"
  ".Colorb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Struct_2eproto_deps[2] = {
  &::descriptor_table_Enum_2eproto,
  &::descriptor_table_Types_2eproto,
};
static ::_pbi::once_flag descriptor_table_Struct_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Struct_2eproto = {
    false, false, 614, descriptor_table_protodef_Struct_2eproto,
    "Struct.proto",
    &descriptor_table_Struct_2eproto_once, descriptor_table_Struct_2eproto_deps, 2, 2,
    schemas, file_default_instances, TableStruct_Struct_2eproto::offsets,
    file_level_metadata_Struct_2eproto, file_level_enum_descriptors_Struct_2eproto,
    file_level_service_descriptors_Struct_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Struct_2eproto_getter() {
  return &descriptor_table_Struct_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Struct_2eproto(&descriptor_table_Struct_2eproto);
namespace Protobuf {

// ===================================================================

class PlayerInfo::_Internal {
 public:
  static const ::Protobuf::Vec2& position(const PlayerInfo* msg);
  static const ::Protobuf::Vec2& velocity(const PlayerInfo* msg);
  static const ::Protobuf::Color& color(const PlayerInfo* msg);
};

const ::Protobuf::Vec2&
PlayerInfo::_Internal::position(const PlayerInfo* msg) {
  return *msg->_impl_.position_;
}
const ::Protobuf::Vec2&
PlayerInfo::_Internal::velocity(const PlayerInfo* msg) {
  return *msg->_impl_.velocity_;
}
const ::Protobuf::Color&
PlayerInfo::_Internal::color(const PlayerInfo* msg) {
  return *msg->_impl_.color_;
}
void PlayerInfo::clear_position() {
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
}
void PlayerInfo::clear_velocity() {
  if (GetArenaForAllocation() == nullptr && _impl_.velocity_ != nullptr) {
    delete _impl_.velocity_;
  }
  _impl_.velocity_ = nullptr;
}
void PlayerInfo::clear_color() {
  if (GetArenaForAllocation() == nullptr && _impl_.color_ != nullptr) {
    delete _impl_.color_;
  }
  _impl_.color_ = nullptr;
}
PlayerInfo::PlayerInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protobuf.PlayerInfo)
}
PlayerInfo::PlayerInfo(const PlayerInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PlayerInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.position_){nullptr}
    , decltype(_impl_.velocity_){nullptr}
    , decltype(_impl_.color_){nullptr}
    , decltype(_impl_.objectid_){}
    , decltype(_impl_.objecttype_){}
    , decltype(_impl_.state_){}
    , decltype(_impl_.facing_){}
    , decltype(_impl_.weapon_){}
    , decltype(_impl_.grounded_){}
    , decltype(_impl_.invincible_){}
    , decltype(_impl_.life_){}
    , decltype(_impl_.kill_cnt_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_position()) {
    _this->_impl_.position_ = new ::Protobuf::Vec2(*from._impl_.position_);
  }
  if (from._internal_has_velocity()) {
    _this->_impl_.velocity_ = new ::Protobuf::Vec2(*from._impl_.velocity_);
  }
  if (from._internal_has_color()) {
    _this->_impl_.color_ = new ::Protobuf::Color(*from._impl_.color_);
  }
  ::memcpy(&_impl_.objectid_, &from._impl_.objectid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.kill_cnt_) -
    reinterpret_cast<char*>(&_impl_.objectid_)) + sizeof(_impl_.kill_cnt_));
  // @@protoc_insertion_point(copy_constructor:Protobuf.PlayerInfo)
}

inline void PlayerInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.position_){nullptr}
    , decltype(_impl_.velocity_){nullptr}
    , decltype(_impl_.color_){nullptr}
    , decltype(_impl_.objectid_){uint64_t{0u}}
    , decltype(_impl_.objecttype_){0}
    , decltype(_impl_.state_){0}
    , decltype(_impl_.facing_){0}
    , decltype(_impl_.weapon_){0}
    , decltype(_impl_.grounded_){false}
    , decltype(_impl_.invincible_){false}
    , decltype(_impl_.life_){0u}
    , decltype(_impl_.kill_cnt_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PlayerInfo::~PlayerInfo() {
  // @@protoc_insertion_point(destructor:Protobuf.PlayerInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PlayerInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.position_;
  if (this != internal_default_instance()) delete _impl_.velocity_;
  if (this != internal_default_instance()) delete _impl_.color_;
}

void PlayerInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PlayerInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:Protobuf.PlayerInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.velocity_ != nullptr) {
    delete _impl_.velocity_;
  }
  _impl_.velocity_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.color_ != nullptr) {
    delete _impl_.color_;
  }
  _impl_.color_ = nullptr;
  ::memset(&_impl_.objectid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.kill_cnt_) -
      reinterpret_cast<char*>(&_impl_.objectid_)) + sizeof(_impl_.kill_cnt_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 objectID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.objectid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protobuf.OBJECT_TYPE objectType = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_objecttype(static_cast<::Protobuf::OBJECT_TYPE>(val));
        } else
          goto handle_unusual;
        continue;
      // .Protobuf.OBJECT_STATE_TYPE state = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_state(static_cast<::Protobuf::OBJECT_STATE_TYPE>(val));
        } else
          goto handle_unusual;
        continue;
      // .Protobuf.Vec2 position = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_position(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protobuf.Vec2 velocity = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_velocity(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool grounded = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.grounded_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protobuf.FACING_TYPE facing = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_facing(static_cast<::Protobuf::FACING_TYPE>(val));
        } else
          goto handle_unusual;
        continue;
      // .Protobuf.WEAPON_TYPE weapon = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_weapon(static_cast<::Protobuf::WEAPON_TYPE>(val));
        } else
          goto handle_unusual;
        continue;
      // .Protobuf.Color color = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_color(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool invincible = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.invincible_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 life = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 88)) {
          _impl_.life_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 kill_cnt = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 96)) {
          _impl_.kill_cnt_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlayerInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protobuf.PlayerInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 objectID = 1;
  if (this->_internal_objectid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_objectid(), target);
  }

  // .Protobuf.OBJECT_TYPE objectType = 2;
  if (this->_internal_objecttype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_objecttype(), target);
  }

  // .Protobuf.OBJECT_STATE_TYPE state = 3;
  if (this->_internal_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_state(), target);
  }

  // .Protobuf.Vec2 position = 4;
  if (this->_internal_has_position()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::position(this),
        _Internal::position(this).GetCachedSize(), target, stream);
  }

  // .Protobuf.Vec2 velocity = 5;
  if (this->_internal_has_velocity()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::velocity(this),
        _Internal::velocity(this).GetCachedSize(), target, stream);
  }

  // bool grounded = 6;
  if (this->_internal_grounded() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(6, this->_internal_grounded(), target);
  }

  // .Protobuf.FACING_TYPE facing = 7;
  if (this->_internal_facing() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      7, this->_internal_facing(), target);
  }

  // .Protobuf.WEAPON_TYPE weapon = 8;
  if (this->_internal_weapon() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      8, this->_internal_weapon(), target);
  }

  // .Protobuf.Color color = 9;
  if (this->_internal_has_color()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(9, _Internal::color(this),
        _Internal::color(this).GetCachedSize(), target, stream);
  }

  // bool invincible = 10;
  if (this->_internal_invincible() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(10, this->_internal_invincible(), target);
  }

  // uint32 life = 11;
  if (this->_internal_life() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(11, this->_internal_life(), target);
  }

  // uint32 kill_cnt = 12;
  if (this->_internal_kill_cnt() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(12, this->_internal_kill_cnt(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protobuf.PlayerInfo)
  return target;
}

size_t PlayerInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protobuf.PlayerInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Protobuf.Vec2 position = 4;
  if (this->_internal_has_position()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.position_);
  }

  // .Protobuf.Vec2 velocity = 5;
  if (this->_internal_has_velocity()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.velocity_);
  }

  // .Protobuf.Color color = 9;
  if (this->_internal_has_color()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.color_);
  }

  // uint64 objectID = 1;
  if (this->_internal_objectid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_objectid());
  }

  // .Protobuf.OBJECT_TYPE objectType = 2;
  if (this->_internal_objecttype() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_objecttype());
  }

  // .Protobuf.OBJECT_STATE_TYPE state = 3;
  if (this->_internal_state() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_state());
  }

  // .Protobuf.FACING_TYPE facing = 7;
  if (this->_internal_facing() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_facing());
  }

  // .Protobuf.WEAPON_TYPE weapon = 8;
  if (this->_internal_weapon() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_weapon());
  }

  // bool grounded = 6;
  if (this->_internal_grounded() != 0) {
    total_size += 1 + 1;
  }

  // bool invincible = 10;
  if (this->_internal_invincible() != 0) {
    total_size += 1 + 1;
  }

  // uint32 life = 11;
  if (this->_internal_life() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_life());
  }

  // uint32 kill_cnt = 12;
  if (this->_internal_kill_cnt() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_kill_cnt());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PlayerInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerInfo::GetClassData() const { return &_class_data_; }


void PlayerInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PlayerInfo*>(&to_msg);
  auto& from = static_cast<const PlayerInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protobuf.PlayerInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_position()) {
    _this->_internal_mutable_position()->::Protobuf::Vec2::MergeFrom(
        from._internal_position());
  }
  if (from._internal_has_velocity()) {
    _this->_internal_mutable_velocity()->::Protobuf::Vec2::MergeFrom(
        from._internal_velocity());
  }
  if (from._internal_has_color()) {
    _this->_internal_mutable_color()->::Protobuf::Color::MergeFrom(
        from._internal_color());
  }
  if (from._internal_objectid() != 0) {
    _this->_internal_set_objectid(from._internal_objectid());
  }
  if (from._internal_objecttype() != 0) {
    _this->_internal_set_objecttype(from._internal_objecttype());
  }
  if (from._internal_state() != 0) {
    _this->_internal_set_state(from._internal_state());
  }
  if (from._internal_facing() != 0) {
    _this->_internal_set_facing(from._internal_facing());
  }
  if (from._internal_weapon() != 0) {
    _this->_internal_set_weapon(from._internal_weapon());
  }
  if (from._internal_grounded() != 0) {
    _this->_internal_set_grounded(from._internal_grounded());
  }
  if (from._internal_invincible() != 0) {
    _this->_internal_set_invincible(from._internal_invincible());
  }
  if (from._internal_life() != 0) {
    _this->_internal_set_life(from._internal_life());
  }
  if (from._internal_kill_cnt() != 0) {
    _this->_internal_set_kill_cnt(from._internal_kill_cnt());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerInfo::CopyFrom(const PlayerInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protobuf.PlayerInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerInfo::IsInitialized() const {
  return true;
}

void PlayerInfo::InternalSwap(PlayerInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerInfo, _impl_.kill_cnt_)
      + sizeof(PlayerInfo::_impl_.kill_cnt_)
      - PROTOBUF_FIELD_OFFSET(PlayerInfo, _impl_.position_)>(
          reinterpret_cast<char*>(&_impl_.position_),
          reinterpret_cast<char*>(&other->_impl_.position_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Struct_2eproto_getter, &descriptor_table_Struct_2eproto_once,
      file_level_metadata_Struct_2eproto[0]);
}

// ===================================================================

class BulletInfo::_Internal {
 public:
  static const ::Protobuf::Vec2& position(const BulletInfo* msg);
  static const ::Protobuf::Vec2& velocity(const BulletInfo* msg);
  static const ::Protobuf::Color& color(const BulletInfo* msg);
};

const ::Protobuf::Vec2&
BulletInfo::_Internal::position(const BulletInfo* msg) {
  return *msg->_impl_.position_;
}
const ::Protobuf::Vec2&
BulletInfo::_Internal::velocity(const BulletInfo* msg) {
  return *msg->_impl_.velocity_;
}
const ::Protobuf::Color&
BulletInfo::_Internal::color(const BulletInfo* msg) {
  return *msg->_impl_.color_;
}
void BulletInfo::clear_position() {
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
}
void BulletInfo::clear_velocity() {
  if (GetArenaForAllocation() == nullptr && _impl_.velocity_ != nullptr) {
    delete _impl_.velocity_;
  }
  _impl_.velocity_ = nullptr;
}
void BulletInfo::clear_color() {
  if (GetArenaForAllocation() == nullptr && _impl_.color_ != nullptr) {
    delete _impl_.color_;
  }
  _impl_.color_ = nullptr;
}
BulletInfo::BulletInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protobuf.BulletInfo)
}
BulletInfo::BulletInfo(const BulletInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BulletInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.position_){nullptr}
    , decltype(_impl_.velocity_){nullptr}
    , decltype(_impl_.color_){nullptr}
    , decltype(_impl_.objectid_){}
    , decltype(_impl_.ownerid_){}
    , decltype(_impl_.facing_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_position()) {
    _this->_impl_.position_ = new ::Protobuf::Vec2(*from._impl_.position_);
  }
  if (from._internal_has_velocity()) {
    _this->_impl_.velocity_ = new ::Protobuf::Vec2(*from._impl_.velocity_);
  }
  if (from._internal_has_color()) {
    _this->_impl_.color_ = new ::Protobuf::Color(*from._impl_.color_);
  }
  ::memcpy(&_impl_.objectid_, &from._impl_.objectid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.facing_) -
    reinterpret_cast<char*>(&_impl_.objectid_)) + sizeof(_impl_.facing_));
  // @@protoc_insertion_point(copy_constructor:Protobuf.BulletInfo)
}

inline void BulletInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.position_){nullptr}
    , decltype(_impl_.velocity_){nullptr}
    , decltype(_impl_.color_){nullptr}
    , decltype(_impl_.objectid_){uint64_t{0u}}
    , decltype(_impl_.ownerid_){uint64_t{0u}}
    , decltype(_impl_.facing_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BulletInfo::~BulletInfo() {
  // @@protoc_insertion_point(destructor:Protobuf.BulletInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BulletInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.position_;
  if (this != internal_default_instance()) delete _impl_.velocity_;
  if (this != internal_default_instance()) delete _impl_.color_;
}

void BulletInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BulletInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:Protobuf.BulletInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.velocity_ != nullptr) {
    delete _impl_.velocity_;
  }
  _impl_.velocity_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.color_ != nullptr) {
    delete _impl_.color_;
  }
  _impl_.color_ = nullptr;
  ::memset(&_impl_.objectid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.facing_) -
      reinterpret_cast<char*>(&_impl_.objectid_)) + sizeof(_impl_.facing_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BulletInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 objectID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.objectid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 ownerID = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.ownerid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protobuf.Vec2 position = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_position(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protobuf.Vec2 velocity = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_velocity(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protobuf.FACING_TYPE facing = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_facing(static_cast<::Protobuf::FACING_TYPE>(val));
        } else
          goto handle_unusual;
        continue;
      // .Protobuf.Color color = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_color(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BulletInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protobuf.BulletInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 objectID = 1;
  if (this->_internal_objectid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_objectid(), target);
  }

  // uint64 ownerID = 2;
  if (this->_internal_ownerid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_ownerid(), target);
  }

  // .Protobuf.Vec2 position = 3;
  if (this->_internal_has_position()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::position(this),
        _Internal::position(this).GetCachedSize(), target, stream);
  }

  // .Protobuf.Vec2 velocity = 4;
  if (this->_internal_has_velocity()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::velocity(this),
        _Internal::velocity(this).GetCachedSize(), target, stream);
  }

  // .Protobuf.FACING_TYPE facing = 5;
  if (this->_internal_facing() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      5, this->_internal_facing(), target);
  }

  // .Protobuf.Color color = 6;
  if (this->_internal_has_color()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::color(this),
        _Internal::color(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protobuf.BulletInfo)
  return target;
}

size_t BulletInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protobuf.BulletInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Protobuf.Vec2 position = 3;
  if (this->_internal_has_position()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.position_);
  }

  // .Protobuf.Vec2 velocity = 4;
  if (this->_internal_has_velocity()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.velocity_);
  }

  // .Protobuf.Color color = 6;
  if (this->_internal_has_color()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.color_);
  }

  // uint64 objectID = 1;
  if (this->_internal_objectid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_objectid());
  }

  // uint64 ownerID = 2;
  if (this->_internal_ownerid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_ownerid());
  }

  // .Protobuf.FACING_TYPE facing = 5;
  if (this->_internal_facing() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_facing());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BulletInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BulletInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BulletInfo::GetClassData() const { return &_class_data_; }


void BulletInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BulletInfo*>(&to_msg);
  auto& from = static_cast<const BulletInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protobuf.BulletInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_position()) {
    _this->_internal_mutable_position()->::Protobuf::Vec2::MergeFrom(
        from._internal_position());
  }
  if (from._internal_has_velocity()) {
    _this->_internal_mutable_velocity()->::Protobuf::Vec2::MergeFrom(
        from._internal_velocity());
  }
  if (from._internal_has_color()) {
    _this->_internal_mutable_color()->::Protobuf::Color::MergeFrom(
        from._internal_color());
  }
  if (from._internal_objectid() != 0) {
    _this->_internal_set_objectid(from._internal_objectid());
  }
  if (from._internal_ownerid() != 0) {
    _this->_internal_set_ownerid(from._internal_ownerid());
  }
  if (from._internal_facing() != 0) {
    _this->_internal_set_facing(from._internal_facing());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BulletInfo::CopyFrom(const BulletInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protobuf.BulletInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BulletInfo::IsInitialized() const {
  return true;
}

void BulletInfo::InternalSwap(BulletInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BulletInfo, _impl_.facing_)
      + sizeof(BulletInfo::_impl_.facing_)
      - PROTOBUF_FIELD_OFFSET(BulletInfo, _impl_.position_)>(
          reinterpret_cast<char*>(&_impl_.position_),
          reinterpret_cast<char*>(&other->_impl_.position_));
}

::PROTOBUF_NAMESPACE_ID::Metadata BulletInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Struct_2eproto_getter, &descriptor_table_Struct_2eproto_once,
      file_level_metadata_Struct_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protobuf::PlayerInfo*
Arena::CreateMaybeMessage< ::Protobuf::PlayerInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protobuf::PlayerInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::Protobuf::BulletInfo*
Arena::CreateMaybeMessage< ::Protobuf::BulletInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protobuf::BulletInfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
