// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Struct.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Struct_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Struct_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Struct_2eproto;
namespace Protobuf {
class ObjectInfo;
struct ObjectInfoDefaultTypeInternal;
extern ObjectInfoDefaultTypeInternal _ObjectInfo_default_instance_;
}  // namespace Protobuf
PROTOBUF_NAMESPACE_OPEN
template<> ::Protobuf::ObjectInfo* Arena::CreateMaybeMessage<::Protobuf::ObjectInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protobuf {

enum PlayerType : int {
  PLAYER_TYPE_NONE = 0,
  PlayerType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PlayerType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PlayerType_IsValid(int value);
constexpr PlayerType PlayerType_MIN = PLAYER_TYPE_NONE;
constexpr PlayerType PlayerType_MAX = PLAYER_TYPE_NONE;
constexpr int PlayerType_ARRAYSIZE = PlayerType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PlayerType_descriptor();
template<typename T>
inline const std::string& PlayerType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PlayerType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PlayerType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PlayerType_descriptor(), enum_t_value);
}
inline bool PlayerType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PlayerType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PlayerType>(
    PlayerType_descriptor(), name, value);
}
// ===================================================================

class ObjectInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protobuf.ObjectInfo) */ {
 public:
  inline ObjectInfo() : ObjectInfo(nullptr) {}
  ~ObjectInfo() override;
  explicit PROTOBUF_CONSTEXPR ObjectInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ObjectInfo(const ObjectInfo& from);
  ObjectInfo(ObjectInfo&& from) noexcept
    : ObjectInfo() {
    *this = ::std::move(from);
  }

  inline ObjectInfo& operator=(const ObjectInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObjectInfo& operator=(ObjectInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ObjectInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ObjectInfo* internal_default_instance() {
    return reinterpret_cast<const ObjectInfo*>(
               &_ObjectInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ObjectInfo& a, ObjectInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ObjectInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ObjectInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ObjectInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ObjectInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ObjectInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ObjectInfo& from) {
    ObjectInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObjectInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protobuf.ObjectInfo";
  }
  protected:
  explicit ObjectInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectIDFieldNumber = 1,
    kObjectTypeFieldNumber = 2,
    kStateFieldNumber = 3,
    kPosXFieldNumber = 4,
    kPosYFieldNumber = 5,
    kVelocityXFieldNumber = 6,
    kVelocityYFieldNumber = 7,
    kGroundedFieldNumber = 8,
    kFacingFieldNumber = 9,
    kWeaponFieldNumber = 10,
  };
  // uint64 objectID = 1;
  void clear_objectid();
  uint64_t objectid() const;
  void set_objectid(uint64_t value);
  private:
  uint64_t _internal_objectid() const;
  void _internal_set_objectid(uint64_t value);
  public:

  // .Protobuf.OBJECT_TYPE objectType = 2;
  void clear_objecttype();
  ::Protobuf::OBJECT_TYPE objecttype() const;
  void set_objecttype(::Protobuf::OBJECT_TYPE value);
  private:
  ::Protobuf::OBJECT_TYPE _internal_objecttype() const;
  void _internal_set_objecttype(::Protobuf::OBJECT_TYPE value);
  public:

  // .Protobuf.OBJECT_STATE_TYPE state = 3;
  void clear_state();
  ::Protobuf::OBJECT_STATE_TYPE state() const;
  void set_state(::Protobuf::OBJECT_STATE_TYPE value);
  private:
  ::Protobuf::OBJECT_STATE_TYPE _internal_state() const;
  void _internal_set_state(::Protobuf::OBJECT_STATE_TYPE value);
  public:

  // float posX = 4;
  void clear_posx();
  float posx() const;
  void set_posx(float value);
  private:
  float _internal_posx() const;
  void _internal_set_posx(float value);
  public:

  // float posY = 5;
  void clear_posy();
  float posy() const;
  void set_posy(float value);
  private:
  float _internal_posy() const;
  void _internal_set_posy(float value);
  public:

  // float velocityX = 6;
  void clear_velocityx();
  float velocityx() const;
  void set_velocityx(float value);
  private:
  float _internal_velocityx() const;
  void _internal_set_velocityx(float value);
  public:

  // float velocityY = 7;
  void clear_velocityy();
  float velocityy() const;
  void set_velocityy(float value);
  private:
  float _internal_velocityy() const;
  void _internal_set_velocityy(float value);
  public:

  // bool grounded = 8;
  void clear_grounded();
  bool grounded() const;
  void set_grounded(bool value);
  private:
  bool _internal_grounded() const;
  void _internal_set_grounded(bool value);
  public:

  // .Protobuf.FACING_TYPE facing = 9;
  void clear_facing();
  ::Protobuf::FACING_TYPE facing() const;
  void set_facing(::Protobuf::FACING_TYPE value);
  private:
  ::Protobuf::FACING_TYPE _internal_facing() const;
  void _internal_set_facing(::Protobuf::FACING_TYPE value);
  public:

  // .Protobuf.WEAPON_TYPE weapon = 10;
  void clear_weapon();
  ::Protobuf::WEAPON_TYPE weapon() const;
  void set_weapon(::Protobuf::WEAPON_TYPE value);
  private:
  ::Protobuf::WEAPON_TYPE _internal_weapon() const;
  void _internal_set_weapon(::Protobuf::WEAPON_TYPE value);
  public:

  // @@protoc_insertion_point(class_scope:Protobuf.ObjectInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t objectid_;
    int objecttype_;
    int state_;
    float posx_;
    float posy_;
    float velocityx_;
    float velocityy_;
    bool grounded_;
    int facing_;
    int weapon_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ObjectInfo

// uint64 objectID = 1;
inline void ObjectInfo::clear_objectid() {
  _impl_.objectid_ = uint64_t{0u};
}
inline uint64_t ObjectInfo::_internal_objectid() const {
  return _impl_.objectid_;
}
inline uint64_t ObjectInfo::objectid() const {
  // @@protoc_insertion_point(field_get:Protobuf.ObjectInfo.objectID)
  return _internal_objectid();
}
inline void ObjectInfo::_internal_set_objectid(uint64_t value) {
  
  _impl_.objectid_ = value;
}
inline void ObjectInfo::set_objectid(uint64_t value) {
  _internal_set_objectid(value);
  // @@protoc_insertion_point(field_set:Protobuf.ObjectInfo.objectID)
}

// .Protobuf.OBJECT_TYPE objectType = 2;
inline void ObjectInfo::clear_objecttype() {
  _impl_.objecttype_ = 0;
}
inline ::Protobuf::OBJECT_TYPE ObjectInfo::_internal_objecttype() const {
  return static_cast< ::Protobuf::OBJECT_TYPE >(_impl_.objecttype_);
}
inline ::Protobuf::OBJECT_TYPE ObjectInfo::objecttype() const {
  // @@protoc_insertion_point(field_get:Protobuf.ObjectInfo.objectType)
  return _internal_objecttype();
}
inline void ObjectInfo::_internal_set_objecttype(::Protobuf::OBJECT_TYPE value) {
  
  _impl_.objecttype_ = value;
}
inline void ObjectInfo::set_objecttype(::Protobuf::OBJECT_TYPE value) {
  _internal_set_objecttype(value);
  // @@protoc_insertion_point(field_set:Protobuf.ObjectInfo.objectType)
}

// .Protobuf.OBJECT_STATE_TYPE state = 3;
inline void ObjectInfo::clear_state() {
  _impl_.state_ = 0;
}
inline ::Protobuf::OBJECT_STATE_TYPE ObjectInfo::_internal_state() const {
  return static_cast< ::Protobuf::OBJECT_STATE_TYPE >(_impl_.state_);
}
inline ::Protobuf::OBJECT_STATE_TYPE ObjectInfo::state() const {
  // @@protoc_insertion_point(field_get:Protobuf.ObjectInfo.state)
  return _internal_state();
}
inline void ObjectInfo::_internal_set_state(::Protobuf::OBJECT_STATE_TYPE value) {
  
  _impl_.state_ = value;
}
inline void ObjectInfo::set_state(::Protobuf::OBJECT_STATE_TYPE value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:Protobuf.ObjectInfo.state)
}

// float posX = 4;
inline void ObjectInfo::clear_posx() {
  _impl_.posx_ = 0;
}
inline float ObjectInfo::_internal_posx() const {
  return _impl_.posx_;
}
inline float ObjectInfo::posx() const {
  // @@protoc_insertion_point(field_get:Protobuf.ObjectInfo.posX)
  return _internal_posx();
}
inline void ObjectInfo::_internal_set_posx(float value) {
  
  _impl_.posx_ = value;
}
inline void ObjectInfo::set_posx(float value) {
  _internal_set_posx(value);
  // @@protoc_insertion_point(field_set:Protobuf.ObjectInfo.posX)
}

// float posY = 5;
inline void ObjectInfo::clear_posy() {
  _impl_.posy_ = 0;
}
inline float ObjectInfo::_internal_posy() const {
  return _impl_.posy_;
}
inline float ObjectInfo::posy() const {
  // @@protoc_insertion_point(field_get:Protobuf.ObjectInfo.posY)
  return _internal_posy();
}
inline void ObjectInfo::_internal_set_posy(float value) {
  
  _impl_.posy_ = value;
}
inline void ObjectInfo::set_posy(float value) {
  _internal_set_posy(value);
  // @@protoc_insertion_point(field_set:Protobuf.ObjectInfo.posY)
}

// float velocityX = 6;
inline void ObjectInfo::clear_velocityx() {
  _impl_.velocityx_ = 0;
}
inline float ObjectInfo::_internal_velocityx() const {
  return _impl_.velocityx_;
}
inline float ObjectInfo::velocityx() const {
  // @@protoc_insertion_point(field_get:Protobuf.ObjectInfo.velocityX)
  return _internal_velocityx();
}
inline void ObjectInfo::_internal_set_velocityx(float value) {
  
  _impl_.velocityx_ = value;
}
inline void ObjectInfo::set_velocityx(float value) {
  _internal_set_velocityx(value);
  // @@protoc_insertion_point(field_set:Protobuf.ObjectInfo.velocityX)
}

// float velocityY = 7;
inline void ObjectInfo::clear_velocityy() {
  _impl_.velocityy_ = 0;
}
inline float ObjectInfo::_internal_velocityy() const {
  return _impl_.velocityy_;
}
inline float ObjectInfo::velocityy() const {
  // @@protoc_insertion_point(field_get:Protobuf.ObjectInfo.velocityY)
  return _internal_velocityy();
}
inline void ObjectInfo::_internal_set_velocityy(float value) {
  
  _impl_.velocityy_ = value;
}
inline void ObjectInfo::set_velocityy(float value) {
  _internal_set_velocityy(value);
  // @@protoc_insertion_point(field_set:Protobuf.ObjectInfo.velocityY)
}

// bool grounded = 8;
inline void ObjectInfo::clear_grounded() {
  _impl_.grounded_ = false;
}
inline bool ObjectInfo::_internal_grounded() const {
  return _impl_.grounded_;
}
inline bool ObjectInfo::grounded() const {
  // @@protoc_insertion_point(field_get:Protobuf.ObjectInfo.grounded)
  return _internal_grounded();
}
inline void ObjectInfo::_internal_set_grounded(bool value) {
  
  _impl_.grounded_ = value;
}
inline void ObjectInfo::set_grounded(bool value) {
  _internal_set_grounded(value);
  // @@protoc_insertion_point(field_set:Protobuf.ObjectInfo.grounded)
}

// .Protobuf.FACING_TYPE facing = 9;
inline void ObjectInfo::clear_facing() {
  _impl_.facing_ = 0;
}
inline ::Protobuf::FACING_TYPE ObjectInfo::_internal_facing() const {
  return static_cast< ::Protobuf::FACING_TYPE >(_impl_.facing_);
}
inline ::Protobuf::FACING_TYPE ObjectInfo::facing() const {
  // @@protoc_insertion_point(field_get:Protobuf.ObjectInfo.facing)
  return _internal_facing();
}
inline void ObjectInfo::_internal_set_facing(::Protobuf::FACING_TYPE value) {
  
  _impl_.facing_ = value;
}
inline void ObjectInfo::set_facing(::Protobuf::FACING_TYPE value) {
  _internal_set_facing(value);
  // @@protoc_insertion_point(field_set:Protobuf.ObjectInfo.facing)
}

// .Protobuf.WEAPON_TYPE weapon = 10;
inline void ObjectInfo::clear_weapon() {
  _impl_.weapon_ = 0;
}
inline ::Protobuf::WEAPON_TYPE ObjectInfo::_internal_weapon() const {
  return static_cast< ::Protobuf::WEAPON_TYPE >(_impl_.weapon_);
}
inline ::Protobuf::WEAPON_TYPE ObjectInfo::weapon() const {
  // @@protoc_insertion_point(field_get:Protobuf.ObjectInfo.weapon)
  return _internal_weapon();
}
inline void ObjectInfo::_internal_set_weapon(::Protobuf::WEAPON_TYPE value) {
  
  _impl_.weapon_ = value;
}
inline void ObjectInfo::set_weapon(::Protobuf::WEAPON_TYPE value) {
  _internal_set_weapon(value);
  // @@protoc_insertion_point(field_set:Protobuf.ObjectInfo.weapon)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protobuf

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Protobuf::PlayerType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protobuf::PlayerType>() {
  return ::Protobuf::PlayerType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
